/**
 * GAO216031A Native Event Types
 *
 * Field names and types are taken directly from the GAO216031A User Manual.
 * These are application-level types used within Aperture for real hardware ingestion.
 *
 * Timestamp format documented by GAO manual: "yyyy-MM-dd HH:mm:ss.SSS"
 */

// ---------------------------------------------------------------------------
// GAO Native Event (exact field names from GAO216031A User Manual)
// ---------------------------------------------------------------------------

export interface GaoNativeEvent {
  /** Tag read timestamp — GAO format: "yyyy-MM-dd HH:mm:ss.SSS" */
  timestamp: string;
  /** EPC memory bank value */
  epc: string;
  /** TID memory bank value (may be empty) */
  tid?: string;
  /** User memory bank value (may be empty) */
  userdata?: string;
  /** Reserved memory bank value (may be empty) */
  reserved?: string;
  /** Antenna number (1-based) */
  ant: number;
  /** RSSI in dBm (negative integer) */
  rssi: number;
  /** Frequency in kHz (e.g. 915000) */
  freq: number;
  /** Phase angle */
  phase: number;
  /** Read count for this tag in this inventory cycle */
  readcount: number;
  /** Reader factory serial number */
  serialno: string;
  /** Customer code (may be empty) */
  customcode?: string;
}

// ---------------------------------------------------------------------------
// Normalized Aperture RFID Event
// Bridges GAO native payload into Aperture's telemetry and MongoDB model.
// ---------------------------------------------------------------------------

export type RfidEventSource = 'gao216031a' | 'http_push' | 'mqtt' | 'llrp' | 'other';

export interface NormalizedRfidEvent {
  /** Unique event identifier generated by Aperture */
  eventId: string;
  /** Data source identifier */
  source: RfidEventSource;
  /** Aperture reader ID (from hardware_readers collection) */
  readerId: string;
  /** GAO reader serial number */
  readerSerial?: string;
  /** ISO 8601 timestamp (converted from GAO format) */
  timestamp: string;
  /** EPC value (primary tag identifier used throughout Aperture) */
  epc: string;
  /** TID value (optional) */
  tid?: string;
  /** Antenna number (1-based) */
  antenna: number;
  /** RSSI in dBm */
  rssi?: number;
  /** Frequency in kHz */
  frequency?: number;
  /** Phase angle */
  phase?: number;
  /** Read count in this inventory cycle */
  readCount?: number;
  /** User memory */
  userData?: string;
  /** Reserved memory */
  reserved?: string;
  /** Customer code */
  customerCode?: string;
  /** Preserved original GAO payload for debugging/audit */
  rawPayload?: GaoNativeEvent;
}
