/**
 * GAO216031A Native Event Types
 *
 * Field names and types are taken directly from the GAO216031A User Manual.
 * These are application-level types used within Aperture.
 * They are NOT an official GAO SDK or official GAO OpenAPI contract.
 *
 * Timestamp format documented by GAO manual: "yyyy-MM-dd HH:mm:ss.SSS"
 */

// ---------------------------------------------------------------------------
// GAO Native Event (exact field names from GAO216031A User Manual)
// ---------------------------------------------------------------------------

export interface GaoNativeEvent {
  /** Tag read timestamp — GAO format: "yyyy-MM-dd HH:mm:ss.SSS" */
  timestamp: string;
  /** EPC memory bank value */
  epc: string;
  /** TID memory bank value (may be empty) */
  tid?: string;
  /** User memory bank value (may be empty) */
  userdata?: string;
  /** Reserved memory bank value (may be empty) */
  reserved?: string;
  /** Antenna number (1-based) */
  ant: number;
  /** RSSI in dBm (negative integer) */
  rssi: number;
  /** Frequency in kHz (e.g. 915000) */
  freq: number;
  /** Phase angle */
  phase: number;
  /** Read count for this tag in this inventory cycle */
  readcount: number;
  /** Reader factory serial number */
  serialno: string;
  /** Customer code (may be empty) */
  customcode?: string;
}

// ---------------------------------------------------------------------------
// Normalized Aperture RFID Event
// Bridges GAO native payload into Aperture's existing telemetry model.
// Extends/complements the existing TelemetryPayload in aiPipeline.ts.
// ---------------------------------------------------------------------------

export type RfidEventSource = 'gao216031a' | 'mock_gao216031a' | 'http_push' | 'mqtt' | 'llrp' | 'other';

export interface NormalizedRfidEvent {
  /** Unique event identifier generated by Aperture */
  eventId: string;
  /** Data source identifier */
  source: RfidEventSource;
  /** Aperture reader ID (from hardware_readers collection) */
  readerId: string;
  /** GAO reader serial number */
  readerSerial?: string;
  /** ISO 8601 timestamp (converted from GAO format) */
  timestamp: string;
  /** EPC value (primary tag identifier used throughout Aperture) */
  epc: string;
  /** TID value (optional) */
  tid?: string;
  /** Antenna number (1-based) */
  antenna: number;
  /** RSSI in dBm */
  rssi?: number;
  /** Frequency in kHz */
  frequency?: number;
  /** Phase angle */
  phase?: number;
  /** Read count in this inventory cycle */
  readCount?: number;
  /** User memory */
  userData?: string;
  /** Reserved memory */
  reserved?: string;
  /** Customer code */
  customerCode?: string;
  /** Preserved original GAO payload for debugging/audit */
  rawPayload?: GaoNativeEvent;
}

// ---------------------------------------------------------------------------
// Mock Reader Configuration
// ---------------------------------------------------------------------------

export type SimulationScenario =
  | 'construction_site_movement'
  | 'random'
  | 'restricted_zone_breach'
  | 'lone_worker'
  | 'mass_evacuation';

export interface MockAntennaConfig {
  /** Antenna port number (1-based) */
  port: number;
  /** Zone name this antenna covers */
  zoneName: string;
  /** Zone ID in Aperture */
  zoneId: string;
}

export interface MockReaderConfig {
  /** Aperture reader ID */
  readerId: string;
  /** Display name */
  name: string;
  /** GAO model string */
  model: string;
  /** Mock serial number — clearly not a physical device */
  serialNumber: string;
  /** Simulated IP address (GAO default documented as 192.168.1.116) */
  ipAddress: string;
  /** Simulated port (GAO default documented as 9090) */
  port: number;
  /** Antennas and their zone mappings */
  antennas: MockAntennaConfig[];
}

export interface SimulatorConfig {
  /** Number of mock readers */
  readerCount: number;
  /** Tags per reader to cycle through */
  tagCount: number;
  /** Tag EPC values to simulate */
  epcs: string[];
  /** Read interval in milliseconds */
  intervalMs: number;
  /** Minimum RSSI (dBm, negative) */
  rssiMin: number;
  /** Maximum RSSI (dBm, negative) */
  rssiMax: number;
  /** Simulation scenario */
  scenario: SimulationScenario;
  /** Deduplication window in milliseconds — suppress same tag+zone reads within this window */
  dedupWindowMs: number;
  /** Whether to inject an unknown tag periodically */
  unknownTagEnabled: boolean;
  /** Interval for unknown tag injection (ms, 0 = disabled) */
  unknownTagIntervalMs: number;
  /** Mock reader definitions */
  readers: MockReaderConfig[];
}

// ---------------------------------------------------------------------------
// Mock Reader Status
// ---------------------------------------------------------------------------

export type MockReaderConnectionState = 'ONLINE' | 'OFFLINE' | 'RECONNECTING' | 'SCANNING';

export interface MockReaderStatus {
  readerId: string;
  model: string;
  serialNumber: string;
  ipAddress: string;
  port: number;
  /** Always "TCP_SERVER" per GAO documented default */
  connectionMode: 'TCP_SERVER';
  /** Clearly marked as simulated — never presented as physical hardware */
  status: MockReaderConnectionState;
  /** Simulator label — always present so UI can distinguish from real readers */
  simulated: true;
  totalScansGenerated: number;
  lastEventAt?: string;
  lastError?: string;
}

export interface MockSimulatorStatus {
  running: boolean;
  scenario: SimulationScenario;
  readers: MockReaderStatus[];
  totalEventsGenerated: number;
  totalEventsSuppressedByDedup: number;
  startedAt?: string;
  config?: Partial<SimulatorConfig>;
}

// ---------------------------------------------------------------------------
// Default Configuration
// ---------------------------------------------------------------------------

/** Default simulator configuration based on GAO documented defaults */
export const DEFAULT_SIMULATOR_CONFIG: SimulatorConfig = {
  readerCount: 2,
  tagCount: 4,
  intervalMs: 500,
  rssiMin: -75,
  rssiMax: -40,
  scenario: 'construction_site_movement',
  dedupWindowMs: 30000,
  unknownTagEnabled: true,
  unknownTagIntervalMs: 60000,
  epcs: [
    'E28068940000501234567891', // EMP001
    'E28068940000501234567892', // EMP002
    'E28068940000501234567893', // EMP003
    'E28068940000501234567894', // EMP004
  ],
  readers: [
    {
      readerId: 'GAO-MOCK-001',
      name: 'GAO216031A Simulator — Gate & Lobby',
      model: 'GAO216031A',
      serialNumber: 'MOCK-GAO-00000001',
      // GAO documented default IP — configurable, not hard-coded in business logic
      ipAddress: process.env.GAO_READER_IP || '192.168.1.116',
      port: Number(process.env.GAO_READER_PORT) || 9090,
      antennas: [
        { port: 1, zoneName: 'Gate 1 / Main Access Gate', zoneId: 'zone_gate_a' },
        { port: 2, zoneName: 'Site Office & Welfare Container', zoneId: 'zone_lobby' },
      ],
    },
    {
      readerId: 'GAO-MOCK-002',
      name: 'GAO216031A Simulator — Production & Restricted',
      model: 'GAO216031A',
      serialNumber: 'MOCK-GAO-00000002',
      ipAddress: process.env.GAO_READER_IP || '192.168.1.117',
      port: Number(process.env.GAO_READER_PORT) || 9090,
      antennas: [
        { port: 1, zoneName: 'Structure & Scaffolding (L1-L4)', zoneId: 'zone_production' },
        { port: 2, zoneName: 'Heavy Crane & Exclusion Area', zoneId: 'zone_restricted' },
      ],
    },
  ],
};

/** Unknown tag EPC — deliberately unmapped to test unknown-tag workflow */
export const UNKNOWN_TAG_EPC = 'E28068940000501234567899';

/**
 * Ordered zone sequence for the "construction_site_movement" scenario.
 * Each person cycles through this path deterministically.
 */
export const CONSTRUCTION_SCENARIO_ZONES: Array<{ zoneName: string; readerId: string; antenna: number }> = [
  { zoneName: 'Gate 1 / Main Access Gate',         readerId: 'GAO-MOCK-001', antenna: 1 },
  { zoneName: 'Site Office & Welfare Container',   readerId: 'GAO-MOCK-001', antenna: 2 },
  { zoneName: 'Structure & Scaffolding (L1-L4)',   readerId: 'GAO-MOCK-002', antenna: 1 },
  { zoneName: 'Heavy Crane & Exclusion Area',      readerId: 'GAO-MOCK-002', antenna: 2 },
  { zoneName: 'Gate 1 / Main Access Gate',         readerId: 'GAO-MOCK-001', antenna: 1 },
];
